version: "3.1"

services:
  email_spam-backend:
    build: 
      context: .
      dockerfile: DockerFile
    working_dir: /app
    image: email_spam-image
    container_name: email_spam-container
    volumes:
      - ./email_spam:/email_spam/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    restart: on-failure
    networks:
      - email_spam-network


networks:
  email_spam-network: